name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - auth-service
          - user-service
          - driver-service
          - location-service
          - ride-service
          - matching-service

    name: Build ${{ matrix.service }}

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          maven-version: '3.9.16'
          cache: maven

      - name: Build
        run: mvn clean package -DskipTests -B
        working-directory: ${{ matrix.service }}
